before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
nfpms:
  - package_name: otel-cli
    homepage: https://github.com/equinix-labs/otel-cli
    description: OpenTelemetry CLI Application (Server & Client)
    license: Apache 2.0
    file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Arch}}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    formats:
      - apk
      - deb
      - rpm
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^demos:'
      - '^configs:'
