receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
processors:
  batch:
exporters:
  debug:
    verbosity: detailed
  otlp/0:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "hGL5WBNfN3HFKdJJ2aVlLF"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,otlp/0]
